# Generated by Django 5.0.4 on 2024-04-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciver", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255)),
                ("balance", models.PositiveIntegerField()),
                ("wallet", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
