# Generated by Django 5.0.4 on 2024-04-18 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="reciver",
            new_name="receiver",
        ),
    ]
